README.md improved with more examples
radareorg/r2yara pull request #37
Opened 2024-10-16 08:08 UTC by seifreed

**Checklist**

- [X] I wrote some documentation

**Description**

Added more documentation with examples for the YARA generation process

2024-10-16 15:54 UTC, trufae requested changes
^

2024-10-16 15:54 UTC, trufae commented on README.md
> +##### Open a binary with radare2:
dont use titles only for enumerating, 5 subtitltes is too much. better just use bold

2024-10-17 17:24 UTC, trufae commented on README.md
> +missing newline
🙄

2024-10-21 12:22 UTC, sylvainpelissier commented
Hi @seifreed thank you for your contribution, can you squash your commits into a single one please ?

2024-10-21 14:18 UTC, trufae commented
@sylvainpelissier you can squash them directly in the web no need to make him do it by hand
<img width="390" alt="Screenshot 2024-10-21 at 16 18 38" src="https://github.com/user-attachments/assets/ed11e1ac-940d-4920-99bf-612e163bb1e3">

2024-10-21 14:27 UTC, sylvainpelissier commented
@trufae it seems something is different for me
![Screenshot from 2024-10-21 16-26-57](https://github.com/user-attachments/assets/950269dc-7c29-42d6-b273-179f76c241ee)

2024-10-21 20:57 UTC, merged